force-app/main/default/objects/NewApptEvent__e/NewApptEvent__e.object-meta.xml
<CustomObject>
    <description>Notify when a user is creating/scheduling a new appointment</description>
    <label>New Appointment</label>
    <pluralLabel>New Appointments</pluralLabel>
</CustomObject>

force-app/main/default/objects/NewApptEvent__e/fields/Customer_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Name__c</fullName>
    <label>Customer Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/EventVFController.cls
// rhys kim
// 05.15.2022
// controller for platform event

public with sharing class EventVFController {
    // listen to platform event
    NewApptEvent__e apptEvent = new NewApptEvent__e(Customer_Name__c = 'New Customer');
    
    Database.SaveResult result = Eventbus.publish(apptEvent);

    if (result.isSuccess()) {
        System.debug('New appointment event successfully published!');
    } else {
        for(Database.Error err : result.getErrors()) {
            System.debug('Error returned: ' +
                         err.getStatusCode() +
                         ' - ' +
                         err.getMessage());
        }
    }
}