force-app/main/default/objects/Vehicle_Part__c/Vehicle_Part__c.object-meta.xml
<CustomObject>
    <description>Tracks inventory of parts for sale and service orders.</description>
    <label>Vehicle Part</label>
    <nameField>
        <label>Vehicle Part Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicle Parts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle_Part__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <defaultValue>&apos;Enter any relevant part information here&apos;</defaultValue>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle_Part__c/fields/Part_Code__c.field-meta.xml
<CustomField>
    <fullName>Part_Code__c</fullName>
    <label>Part Code Number</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Vehicle_Part__c/fields/Part_Number__c.field-meta.xml
<CustomField>
    <fullName>Part_Number__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Part Number</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/MakeSomeParts.cls
public class MakeSomeParts {
	   public static void genParts(Integer n) {
        List<Vehicle_Part__c> parts = new List<Vehicle_Part__c>();
        for(Integer i = 0; i < n; i++) {
            Vehicle_Part__c part = new Vehicle_Part__c();
       		part.Name = 'Part' + i;
            String prefix;
            Decimal x = Math.random();
            Decimal coinToss = (x * 10).round(System.RoundingMode.FLOOR);
            if(coinToss < 5) {
            	prefix = '1';
        	}
        	else {
            	prefix = '2';
        	}
        	part.Part_Number__c = 'P-000' + i;
        	part.Part_Code__c = prefix + '01' + 2 * i;
            part.Description__c = 'This can be screwed or glued to that car or truck of yours!';
        	parts.add(part);
        }
    insert parts;
    }
}