force-app/main/default/objects/Appointment__c/Appointment__c.object-meta.xml
<CustomObject>

    <description>Custom object for tracking sales and service appointments</description>




    <label>Appointment</label>
    <nameField>
        <label>Appointment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>

    <sharingModel>ControlledByParent</sharingModel>

    <sharingModel>ReadWrite</sharingModel>

</CustomObject>

force-app/main/default/objects/Appointment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Appointments</relationshipLabel>
    <relationshipName>Appointments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Salesperson__c.field-meta.xml
<CustomField>
    <fullName>Salesperson__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Salesperson</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>Custom: Sales Profile</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ApptController.cls
public class ApptController {
    
    //create the lists to populate the table showing the appointments
    
    public List<Appointment__c> allSales {
        get {
            return [SELECT Time__c, Salesperson__c, Contact__c, Description__c FROM Appointment__c WHERE Type__c = 'Sales'];
        }
    }
    public List<Appointment__c> salesByDate {
        get{
            if(salesByDate == null) {
                salesByDate = new List<Appointment__c>();
                for(Appointment__c appt : allSales) {
                    salesByDate.add(appt);
                }
            }
        return salesByDate;    
        }
        set;
    }
    
    //create an integer the methods will use to set the date for which to retrieve records
    
    private Integer nDays = 0;
    
    //create a method to display today's sales appointments and reset the day counter
       
    public void apptToday() {
        nDays = 0;
        salesByDate = new List<Appointment__c>();
        for(Appointment__c appt : allSales) {
            if(appt.Time__c.date() == Date.today()) {
            	salesByDate.add(appt);    
            }
        }       
    }
    
    //create a method to move forward a day on every click of the >> button
    
    public void fwdADay() {
        nDays++;
		salesByDate = new List<Appointment__c>();
        for(Appointment__c appt: allSales) {
            if(appt.Time__c.date() == Date.today().addDays(nDays)) {
                salesByDate.add(appt);
            }
        }
    }
    
    //create a method to move back a day on every click of the << button
    
    public void backADay() {
        nDays--;
		salesByDate = new List<Appointment__c>();
        for(Appointment__c appt: allSales) {
            if(appt.Time__c.date() == Date.today().addDays(nDays)) {
                salesByDate.add(appt);
            }
        }
    }
    
    //create a method to reset back to show all appointments
    
    public void reset() {
        salesByDate = null;
    }
}