force-app/main/default/objects/Appointment__c/Appointment__c.object-meta.xml
<CustomObject>

    <description>Custom object for tracking sales and service appointments</description>




    <label>Appointment</label>
    <nameField>
        <label>Appointment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>

    <sharingModel>ControlledByParent</sharingModel>

    <sharingModel>ReadWrite</sharingModel>

</CustomObject>

force-app/main/default/objects/Appointment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Appointments</relationshipLabel>
    <relationshipName>Appointments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CreateApptData.cls
public class CreateApptData {
    public static void genCtact(Integer n, String name) {
        List<Contact> ctc = new List<Contact>();
        for(Integer i = 0; i < n; i++) {
            Contact c = new Contact();
            String nm = name;
            c.LastName = nm + i;
            ctc.add(c);
        }
        insert ctc;
    }
	 public static void genSalesAppt(Integer n, String cname) {
        List<Appointment__c> appmnt = new List<Appointment__c>();
        genCtact(n, cname);
        List<Contact> ct = [SELECT ID FROM Contact];
        for(Integer i = 0; i < n; i++) {
            Decimal x = Math.random();
            Decimal y = (x * n).round(System.RoundingMode.FLOOR);
            Integer j = (Integer)y;
            Decimal randDay = (x * 14).round(System.RoundingMode.FLOOR) + 10;
       	    Decimal randHr = (x * 7).round(System.RoundingMode.FLOOR) + 9;
            Decimal randMn = (x * 59).round(System.RoundingMode.FLOOR);
            String amPM;
            if(randHr -12 < 0) {
               amPM = 'AM';
            }
            else {
               amPM = 'PM';
            }
            if(randHr > 12) {
                randHr = randHr - 12;
            }
            String dt = '5/' + randDay + '/2022,' + randHr + ':' + randMn + ' ' +amPM;
            Datetime aptTime = Datetime.Parse(dt);
            Appointment__c ap = new Appointment__c();
            ap.Name = 'Appointment' + i;
            ap.Contact__c = ct[j].Id;
			ap.Time__c = aptTime;
			ap.Type__c = 'Sales';
            ap.Description__c = 'This is appointment # ' + i;
			appmnt.add(ap);            
        }
        insert appmnt;
    }
}