force-app/main/default/objects/Appointment__c/Appointment__c.object-meta.xml
<CustomObject>

    <description>Custom object for tracking sales and service appointments</description>




    <label>Appointment</label>
    <nameField>
        <label>Appointment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>

    <sharingModel>ControlledByParent</sharingModel>

    <sharingModel>ReadWrite</sharingModel>

</CustomObject>

force-app/main/default/objects/Appointment__c/fields/Salesperson__c.field-meta.xml
<CustomField>
    <fullName>Salesperson__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Salesperson</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>Custom: Sales Profile</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TestApptUtility.cls
@IsTest
public class TestApptUtility {
    
    @TestSetup
    public static void genData() {
        TestData.genAppt(20);
    }
    @IsTest
    public static void testAU() {
        try {
             test.startTest();
             List<Appointment__c> duplicate = [SELECT Salesperson__c, Time__c FROM Appointment__c WHERE Description__c = 'This is Appointment # 0'];
             ApptUtility.noDoubleBooking(duplicate);
             test.stopTest();
        }
        catch(BookingException e) {
            System.assert(e != null);
        }
    }
}